name: Deploy Dev VM with Multipass

on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'Which VM profile to deploy?'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install envsubst
      run: sudo apt-get install -y gettext

    - name: Inject SSH key into cloud-init
      env:
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      run: |
        mkdir -p rendered
        envsubst < vm-profiles/dev.yaml > rendered/dev.yaml

    - name: Launch VM with Multipass
      run: |
        multipass launch --name dev-vm --cloud-init rendered/dev.yaml

    - name: Wait for VM to boot
      run: |
        sleep 20  # Let cloud-init settle
        multipass info dev-vm

    - name: Display IP
      run: multipass info dev-vm | grep IPv4
